package com.partkyle.euler.solutions;

import com.partkyle.euler.Solution;

/* Each new term in the Fibonacci sequence is generated by adding the 
 * previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *     
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

public class Problem2 implements Solution {

	@Override
	public void solve() {
		int i = 0;
		int result = fibonacci(i);
		int sum = 0;
		while (result < 4e6) {
			if (result % 2 == 0)
				sum += result;
			result = fibonacci(i++);
		}
		System.out.println("Problem 2: " + sum);
	}

	public int fibonacci(int n) {
		if (n < 2)
			return 1;
		return fibonacci(n - 1) + fibonacci(n - 2);
	}

	public static void main(String[] args) {
		Solution solution = new Problem2();
		solution.solve();
	}

}
